resources:
  - name: source-repo
    type: git
    icon: github
    source:
      uri: https://github.com/sneakybeaky/haproxy-ami.git
      branch: main
  - name: ami-id
    type: s3
    icon: tag
    source:
      region_name: eu-west-2
      bucket: 566231541642-build-artifacts
      access_key_id: ((build_artifacts_bucket.access_key_id))
      secret_access_key: ((build_artifacts_bucket.secret_access_key))
      versioned_file: haproxy-AMI/amiID
  - name: tfstate
    type: s3
    icon: terraform
    source:
      region_name: eu-west-2
      bucket: 566231541642-build-artifacts
      access_key_id: ((build_artifacts_bucket.access_key_id))
      secret_access_key: ((build_artifacts_bucket.secret_access_key))
      versioned_file: haproxy-AMI/terraform.tfstate
  - name: tfoutput
    type: s3
    icon: format-list-bulleted
    source:
      region_name: eu-west-2
      bucket: 566231541642-build-artifacts
      access_key_id: ((build_artifacts_bucket.access_key_id))
      secret_access_key: ((build_artifacts_bucket.secret_access_key))
      versioned_file: haproxy-AMI/output

jobs:
  - name: build
    plan:
      - get: source-repo
        trigger: true
      - task: "packer build"
        file: source-repo/ci/tasks/build-ami.yaml
        input_mapping:
          source: source-repo
        params:
          AWS_ACCESS_KEY_ID: ((packer_build.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((packer_build.secret_access_key))
          AWS_DEFAULT_REGION: eu-west-2
      - put: ami-id
        params:
          file: ami/id

  - name: deploy-for-tests
    plan:
      - get: ami-id
        passed: [build]
        trigger: true
      - get: source-repo
        passed: [build]
      - task: "create instance"
        file: source-repo/ci/tasks/create-instance.yaml
        input_mapping:
          source: source-repo
        params:
          AWS_ACCESS_KEY_ID: ((ami_test.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((ami_test.secret_access_key))
          AWS_DEFAULT_REGION: eu-west-2
        on_failure:
          task: "destroy instance"
          file: source-repo/ci/tasks/destroy-instance.yaml
          input_mapping:
            source: source-repo
          params:
            AWS_ACCESS_KEY_ID: ((ami_test.access_key_id))
            AWS_SECRET_ACCESS_KEY: ((ami_test.secret_access_key))
            AWS_DEFAULT_REGION: eu-west-2
      - put: tfstate
        params:
          file: tfstate/terraform.tfstate
      - put: tfoutput
        params:
          file: tfoutput/output
  
  - name: test
    plan:
      - get: source-repo
        passed: [deploy-for-tests]
      - get: ami-id
        passed: [deploy-for-tests]
        trigger: true
      - get: tfstate
        passed: [deploy-for-tests]
      - get: tfoutput
        passed: [deploy-for-tests]
      - task: "run tests"
        file: source-repo/ci/tasks/run-tests.yaml
        input_mapping:
          source: source-repo
        params:
          AWS_ACCESS_KEY_ID: ((ami_test.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((ami_test.secret_access_key))
          AWS_DEFAULT_REGION: eu-west-2
  
  - name: publish
    plan:
      - get: source-repo
        passed: [test]
      - get: ami-id
        passed: [test]
        trigger: true
      - task: "tag AMI"
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: amazon/aws-cli
          inputs:
            - name: ami-id
          params:
            AWS_ACCESS_KEY_ID: ((packer_build.access_key_id))
            AWS_SECRET_ACCESS_KEY: ((packer_build.secret_access_key))
            AWS_DEFAULT_REGION: eu-west-2
            AWS_PAGER: ""
          run:
            path: /bin/bash
            args:
              - -exec
              - |
                AMI=$(<ami-id/amiID)
                aws ec2 create-tags --resources $AMI --tags Key=Validated,Value=true

  - name: destroy-tests-env
    plan:
      - get: ami-id
        passed: [publish]
        trigger: true
      - get: tfstate
        passed: [test]
      - get: source-repo
        passed: [publish]
      - task: "destroy instance"
        file: source-repo/ci/tasks/destroy-instance.yaml
        input_mapping:
          source: source-repo
        params:
          AWS_ACCESS_KEY_ID: ((ami_test.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((ami_test.secret_access_key))
          AWS_DEFAULT_REGION: eu-west-2
