platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: 0.11.14

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:

inputs:
  - name: ami-id
  - name: source

outputs:
  - name: tfstate
  - name: tfoutput

run:
  path: /bin/sh
  args:
    - -exec
    - |
      echo "Deploying..."
      AMI=$(cat ami-id/amiID)
      VERSION=$(cat ami-id/version)
      terraform init source/test/terraform-packer
      terraform apply -auto-approve -state-out=tfstate/terraform.tfstate \
        -var "ami_id=$AMI" \
        -var "prefix=$VERSION" \
        -var "aws_region=$AWS_DEFAULT_REGION" \
        -var "instance_name=terratest-http-example-$VERSION" \
        source/test/terraform-packer
      terraform output -state=tfstate/terraform.tfstate > tfoutput/output
